quarkus.datasource.db-kind=sqlite
quarkus.datasource.jdbc.url=jdbc:sqlite:investimentos.db
quarkus.datasource.jdbc.driver=org.sqlite.JDBC

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql

mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=simulador-investimentos
smallrye.jwt.sign.key.location=privateKey.pem

app.autenticacao.username=admin
app.autenticacao.password=admin123
app.autenticacao.token-expiracao-segundos=86400

quarkus.log.console.json=true